### ISSUE TITLE
请问这是出现了什么问题呢？

### ISSUE THREAD

**Issue by onestep1987** [tsukasalx/ykw-whisper#2]
docker installed successfully.
docker-compose installed successfully.
ykw/whisper22.04 build successfully.
Traceback (most recent call last):
  File "/usr/local/bin/whisper", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/whisper/transcribe.py", line 433, in cli
    model = load_model(model_name, device=device, download_root=model_dir)
  File "/usr/local/lib/python3.10/dist-packages/whisper/__init__.py", line 131, in load_model
    checkpoint_file = _download(_MODELS[name], download_root, in_memory)
  File "/usr/local/lib/python3.10/dist-packages/whisper/__init__.py", line 67, in _download
    with urllib.request.urlopen(url) as source, open(download_target, "wb") as output:
OSError: [Errno 30] Read-only file system: './model/medium.pt'

**Comment by onestep1987** [comment]
输入的命令行是  ykw-whisper 1.mkv

**Comment by tsukasalx** [comment]
更新一下吧，修复了很多问题

**Comment by tsukasalx** [comment]
fixed
